# Generated by Django 6.0 on 2026-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='General', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
